# .github/workflows/ai-code-review.yml

name: AI Code Review and Discord Notification

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write # PRへのコメント書き込みに必要
      contents: read # コードの読み取りに必要

    steps:
      # 1. コードのチェックアウト (変更なし)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. CodiumAI PR-Agentを実行 (変更なし)
      - name: Run CodiumAI PR-Agent Review
        id: pr_agent_review
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ... (必要に応じて他のAPIキーなどを追加) ...

      # 3. Discordに通知を送信 (★ Zennの記事を参考に修正)
      - name: Send Discord Notification
        uses: appleboy/discord-action@master # ★ アクション名を変更
        # if: always() # 失敗時も通知したい場合はコメントを外す
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }} # ★ Webhook URLからID部分をSecretに設定
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }} # ★ Webhook URLからToken部分をSecretに設定
          message: | # メッセージ内容
            CodiumAI Review started for PR #${{ github.event.pull_request.number }} ('${{ github.event.pull_request.title }}')
            Review results will be posted as a comment on the PR.
            See PR: ${{ github.event.pull_request.html_url }}